dist: xenial
language: python
python:
- '3.7'
install: pip install pelican beautifulsoup4 pelican-youtube
script:
- make html
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: always

after_success:
- make rsync_upload
